name: Tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Run E2E tests
        if: success()
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config: baseUrl=https://milobella.com:10443
          env: MILOBELLA_USERNAME=${{ secrets.MILOBELLA_USERNAME }},MILOBELLA_PASSWORD=${{ secrets.MILOBELLA_PASSWORD }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
